builds:
  - binary: mackerel-plugin-cuenote-srs-status
    goos:
      - darwin
      - linux
    goarch:
      - amd64
    ldflags:
     - -X main.Version={{.Version}}
archive:
  format: zip
  name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
release:
  github:
    owner: ch1aki
    name: mackerel-plugin-cuenote-srs-status