builds:
  - binary: mackerel-plugin-cuenote-srs-status
    goos:
      - darwin
      - linux
    goarch:
      - amd64
    ldflags:
     - -X main.Version={{.Version}}
archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - format: zip
release:
  github:
    owner: ch1aki
    name: mackerel-plugin-cuenote-srs-status