name: Release
on:
  push:
    branches:
      - "!*"
    tags:
      - "v*"
jobs:
  build:
    runs-on: ubuntu-latest
    name: GoReleaser
    steps:
    - uses: actions/checkout@master
    - name: Set up Go 1.13
      uses: actions/setup-go@v4
      with:
        go-version: 1.13
    - name: Run go mod download
      run: go mod download
    - name: Run GoReleaser
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: curl -sL https://git.io/goreleaser | bash
